import '../models/topic.dart';

List<Topic> groupedByCategory = [
  Topic(
    topicName: 'Auto',
    channelCount: '13',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/auto.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Animation',
    channelCount: '34',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/animation.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Undefined',
    channelCount: '4579',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/undefined.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Business',
    channelCount: '44',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/business.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Classic',
    channelCount: '46',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/classic.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Comedy',
    channelCount: '42',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/comedy.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Cooking',
    channelCount: '19',
    channelUrl: '',
    topicImageUrl: 'https://iptv-org.github.io/iptv/categories/cooking.m3u',
  ),
  Topic(
    topicName: 'Culture',
    channelCount: '26',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/culture.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Documentary',
    channelCount: '40',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/documentary.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Education',
    channelCount: '91',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/education.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Entertainment',
    channelCount: '185',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/entertainment.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Family',
    channelCount: '31',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/family.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'General',
    channelCount: '483',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/general.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Kids',
    channelCount: '150',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/kids.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Legislative',
    channelCount: '112',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/legislative.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Lifestyle',
    channelCount: '61',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/lifestyle.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Movies',
    channelCount: '211',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/movies.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Music',
    channelCount: '279',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/music.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'News',
    channelCount: '373',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/news.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Outdoor',
    channelCount: '40',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/outdoor.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Relax',
    channelCount: '15',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/relax.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Religious',
    channelCount: '236',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/religious.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Series',
    channelCount: '137',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/series.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Science',
    channelCount: '14',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/science.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Shop',
    channelCount: '64',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/shop.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Sports',
    channelCount: '141',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/sports.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Travel',
    channelCount: '16',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/travel.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: 'Weather',
    channelCount: '10',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/weather.m3u',
    topicImageUrl: '',
  ),
  Topic(
    topicName: '18+',
    channelCount: '49',
    channelUrl: 'https://iptv-org.github.io/iptv/categories/xxx.m3u',
    topicImageUrl: '',
  ),
];
